### ISSUE TITLE
Character Model

### ISSUE THREAD

**Issue by 15014576** [14016036/Splash_Attack#3]
@14016036 I see you've made the original character model but i thought we were dropping that garbage bin and using a proper character? Daf was looking into Maximo which has animations for the characters and an actual person character model.

**Comment by 14016036** [comment]
Nah this was just a mock model I needed to make to test the multiplayer.. it can absolutely be changed.. I just needed to actually like confirm models were connecting, being seen via both host and clients and mechanics like shooting were working for both.

**Comment by 15014576** [comment]
Oh fair enough, just wanted to make sure we were on the same page with the character
